Expose a method **generateOutputFile** so it can be called from both sfdx plugin & VsCode Extension
Lightning-Flow-Scanner/lightning-flow-scanner-core pull request #60
Opened 2023-12-16 15:35 UTC by nvuillam

2023-12-17 20:41 UTC, RubenHalman reviewed
Thank you so much for this. LGTM, will you also create the pr for this in the sfdx app simultaneously or how would you like to proceed?

2023-12-17 21:03 UTC, nvuillam commented
@RubenHalman i'll be able to call it from sfdx & VsCode once scanner-core will be released, to be able to upgrade the dependency then call the method :)

2023-12-18 10:42 UTC, RubenHalman commented
@nvuillam Roger that. Please allow me a few days to verify the compatibility/compilation(there should be no issue and this is a small task, but I don't have this automated yet). Meanwhile if you want to work on the sf plugin already, you can import/test local modules by replacing the import statement to point to a module you compile locally, like so: 

Replace: 
`import { RuleResult } from "lightning-flow-scanner-core/out/main/models/RuleResult";
`
With:
`import { RuleResult } from "/Users/rubenhalman/Projects/lightning-flow-scanner-core/lib";`

2023-12-18 10:46 UTC, RubenHalman requested changes

2023-12-18 10:46 UTC, RubenHalman commented on CHANGELOG.md
> +- Expose a method **generateOutputFile** so it can be called from both sfdx plugin & VsCode Extension
@nvuillam Would you be so kind to drop a few lines on the CSV / XLSX functionality features? From what I gather from your pr, it is probably helpful to document the fields exposed: ["Flow API Name", "Rule Name", "Item", "Severity", "Rule description", "Rule Type", "Flow Type", "Flow Label"]. Do you think you can help me write something that I can use as a baseline of instruction for the readme?

2023-12-24 18:14 UTC, nvuillam commented on CHANGELOG.md
> +- Expose a method **generateOutputFile** so it can be called from both sfdx plugin & VsCode Extension
@RubenHalman these are the exact same fields that are output in the console, naming them is probably enough for understanding :)

2024-03-21 13:14 UTC, RubenHalman commented
this pr needs to be rebased on 2.30

2024-03-21 13:14 UTC, closed without merging